class WellLogError(RuntimeError):
    code: str
    def __init__(self, message: str, code: str) -> None: ...

class WellLogValidationError(WellLogError): ...
class WellLogVersionConflict(WellLogError): ...
class WellLogCapabilityError(WellLogError): ...
class WellLogThreadError(WellLogError): ...
class WellLogExportError(WellLogError): ...
